version: "2.6.1"

services:
  mysqldb:
    image: "mysql:latest"
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: library_crud
      MYSQL_USER: librarycruduser
      MYSQL_PASSWORD: LibraryCrudUser123
      MYSQL_ROOT_PASSWORD: LibraryCrudUser123
  application:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysqldb